### ISSUE TITLE
Issue with Custom Prediction Function in the `cubist` Package

### ISSUE THREAD

**Issue by snvv** [tripartio/ale#6]
Hello,

I am working with a non-standard function from the `cubist` package. The `predict` function has the following form:

```r
predict(object, newdata = NULL, neighbors = 0, ...)
```

The `neighbors` parameter is optional but necessary for fitting. The fitting parameter is one of the tuning parameters in caret.

I have tried various implementations of `pred_fun`, such as:

```r
custom_predict <- function(newdata, object, type = pred_type) {
  mypre <- predict(object, newdata[, -ncol(newdata)], neighbors = m.cubist$bestTune$neighbors)
  return(mypre)
}
```

However, nothing seems to work. Clearly, there is something I am missing.

Please note that the `m.cubist.$bestTune$neighbors` obtained from caret tuning.

I also have another question regarding some "strange" interaction plots, but I will create a separate post for that once I have a solution to this issue.

Best regards

**Comment by tripartio** [comment]
Please give me a minimal reproducible example with the full code (including library calls and model training) and show the steps you tried until you got a specific error. Without fully executable code, it is not easy to help you concretely. In particular, when you say, "Please note that the m.cubist.$bestTune$neighbors obtained from caret tuning", I cannot know your exact problem.

**Comment by tripartio** [comment]
Your code does not run as given. For example:

``` r
library(cubist)
#> Error in library(cubist): there is no package called 'cubist'
set.seed(11)
```

<sup>Created on 2024-09-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

and

``` r
# Create training and testing sets
in_train_set <- sample(1:nrow(ames), floor(0.8 * nrow(ames)))
#> Error in eval(expr, envir, enclos): object 'ames' not found
```

<sup>Created on 2024-09-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>


Could you please start a fresh R session, run the code (and fix it) and then post a complete working example?

**Comment by snvv** [comment]
It follows a complete representative example

# Load the necessary library
library(Cubist)

# Load the Ames housing dataset
data(ames, package = "modeldata")

# Model the data on the log10 scale
ames$Sale_Price <- log10(ames$Sale_Price)

# Set seed for reproducibility
set.seed(11)

# Split the data into training and testing sets
in_train_set <- sample(1:nrow(ames), floor(0.8 * nrow(ames)))

# Define the predictors for the model
predictors <- c(
  "Lot_Area", "Alley", "Lot_Shape", "Neighborhood", "Bldg_Type", 
  "Year_Built", "Total_Bsmt_SF", "Central_Air", "Gr_Liv_Area", 
  "Bsmt_Full_Bath", "Bsmt_Half_Bath", "Full_Bath", "Half_Bath", 
  "TotRms_AbvGrd", "Year_Sold", "Longitude", "Latitude"
)

# Create training and testing datasets
train_pred <- ames[in_train_set, predictors]
test_pred  <- ames[-in_train_set, predictors]

train_resp <- ames$Sale_Price[in_train_set]
test_resp  <- ames$Sale_Price[-in_train_set]

# Train a Cubist model with committees = 3
set.seed(1)
com_model <- cubist(x = train_pred, y = train_resp, committees = 3)

# Summarize the model
summary(com_model)

# Make predictions using the test set and neighbors = 5
inst_pred <- predict(com_model, test_pred, neighbors = 5)

# Calculate Root Mean Squared Error (RMSE)
rmse <- sqrt(mean((inst_pred - test_resp)^2))
rmse

**Comment by tripartio** [comment]
Thanks for the complete reproducible example.

I quickly ran into a quirk. The `ale()` function currently requires the y column data to be included in the dataset of the `data` argument. Thus, it must added to the dataset for analysis. (I see that this is overly restrictive; I've made a note to myself to relax this requirement in the next version of the package.) So, let's do that first:

``` r
# Normally, IML (e.g., ALE) is carried out on the full dataset, not just the test set. But this is optional.
ames_pred <- ames |> 
  # ale() function requires the y column data included in the dataset
  dplyr::select(Sale_Price, all_of(predictors))
```

Now, let's try to calculate ALE with default options:

``` r
library(ale)

# First try default ale() options, but error message indicates that y_col must be specified.
cube_ale <- ale(ames_pred, com_model)
#> Error in validate_y_col(y_col = y_col, data = data, model = model): This model seems to be non-standard, so y_col must be provided.
```

As the error message indicates, we need to specify `y_col`:
``` r
# ale() now works with y_col specified, using default Cubist:::predict.cubist() options (neighbors = 0)
cube_ale <- ale(
  ames_pred, com_model,
  y_col = 'Sale_Price'
)
cube_ale$plots$Year_Built
```

![](https://i.imgur.com/cTcSIM8.png)

<sup>Created on 2024-09-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

So, `ale` works easily with `Cubist`.

But, if I understand you correctly, you want to customize the `neighbor` argument of the `predict()` function. There's more than one way that this can be done but I think the most flexible way (to avoid hard-coding the number of neighbours) is to use both a custom predict function and to specially encode the `pred_type` argument:
* The value of the `pred_type` argument will be used to specify the number of neighbours. However, the current version of `ale()` requires `pred_type` to be a character string. So, we can enter the number of neighbours as a string and then convert it to integer inside the custom predict function. (I've made a note for myself to make `pred_type` more flexible in the next version of the package.)
* Create a custom predict function for the `pred_fun` argument that converts `pred_type` to the number of neighbours:

``` r
# To specify neighbors = 5, we need a custom predict function.
# The user will use the ale(pred_type) argument to specify the number of neighbours.
predict_cubist_ale <- function(object, newdata, type = pred_type) {
  Cubist:::predict.cubist(
    object, newdata, 
    # Because the ale(pred_type) argument must be a character, convert it to integer here
    neighbors = as.integer(type)
  )
}

# Specify y_col; to customize neighbors in prediction, both pred_fun and pred_type are needed
cube_ale_5 <- ale(
  ames_pred, com_model,
  y_col = 'Sale_Price',
  pred_fun = predict_cubist_ale,
  # ale(pred_type) must be a character; convert to integer inside the custom pred_fun
  pred_type = '5'
)
cube_ale_5$plots$Year_Built
```

![](https://i.imgur.com/IEd8fJt.png)

<sup>Created on 2024-09-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

I believe this is what you're looking for.

**Comment by tripartio** [comment]
@snvv By the way, thanks for your questions. I really appreciate them. They are helping me verify the robustness of the package and help point out areas that need refinement for real-world usage beyond my personal usage.
